[build]
builder = "railpack"
buildCommand = "echo building!"

[deploy]
preDeployCommand = ["uvicorn main:app --reload"]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"